### ISSUE TITLE
Error on trying examples

### ISSUE THREAD

**Issue by Jrakru** [gdemin/expss#10] opened 2018-10-04 15:45 UTC
I am new to R.  I get the following error message when I try to run the example provided
> Error in name_dots(...) : could not find function "name_dots"

```

library(expss)
data(mtcars)
mtcars = apply_labels(mtcars,
                      mpg = "Miles/(US) gallon",
                      cyl = "Number of cylinders",
                      disp = "Displacement (cu.in.)",
                      hp = "Gross horsepower",
                      drat = "Rear axle ratio",
                      wt = "Weight (1000 lbs)",
                      qsec = "1/4 mile time",
                      vs = "Engine",
                      vs = c("V-engine" = 0,
                             "Straight engine" = 1),
                      am = "Transmission",
                      am = c("Automatic" = 0,
                             "Manual"=1),
                      gear = "Number of forward gears",
                      carb = "Number of carburetors"
)

cro(mtcars$am, mtcars$vs)


```

**Comment by oktep** [comment] 2018-10-05 08:14
Same problem for me

I run name_dots() function from https://github.com/Rdatatable/data.table/blob/master/R/utils.R
 and its working.
script:

name_dots <- function(...) {
  dot_sub <- as.list(substitute(list(...)))[-1L]
  vnames = names(dot_sub)
  if (is.null(vnames)) {
    vnames = rep.int("", length(dot_sub))
    novname = rep.int(TRUE, length(dot_sub))
  } else {
    vnames[is.na(vnames)] = ""
    if (any(vnames==".SD")) stop("A column may not be called .SD. That has special meaning.")
    novname = vnames==""
  }
  for (i in which(novname)) {
    if ((tmp <- deparse(dot_sub[[i]])[1L]) == make.names(tmp))
      vnames[i] = tmp
  }
  still_empty = vnames==""
  if (any(still_empty)) vnames[still_empty] = paste0("V", which(still_empty))
  list(vnames=vnames, novname=novname)
}

**Comment by gdemin** [comment] 2018-10-05 17:57
By now I can not reproduce this issue on my system. For detailed investigation I need output of  the `sessionInfo()` function on your machine.  
Also you can try to reinstall both data.table and expss. Perhaps it will solve the problem.

**Comment by gnkitchen11** [comment] 2018-10-16 15:44
I have the same problem. I have included the code that I ran before the error and the sessionInfo(), if you need more, please let me know. Thanks for your great effort and insight with expss. Gary

Feedback on expss failure.txt (I also attached this txt file, hope it helps.)

Code before failure:
> library(expss)
> data(mtcars)
> # apply_labels() is a function in the expss package
> mtcars <- apply_labels(mtcars,
+                       mpg = "Miles/(US) gallon",
+                       cyl = "Number of cylinders",
+                       disp = "Displacement (cu.in.)",
+                       hp = "Gross horsepower",
+                       drat = "Rear axle ratio",
+                       wt = "Weight (1000 lbs)",
+                       qsec = "1/4 mile time",
+                       vs = "Engine",
+                       vs = c("V-engine" = 0,
+                              "Straight engine" = 1),
+                       am = "Transmission",
+                       am = c("Automatic" = 0,
+                              "Manual"=1),
+                       gear = "Number of forward gears",
+                       carb = "Number of carburetors"
+ )

> # Get a table using base R
> with(mtcars, table(am, vs))
           vs
am          V-engine Straight engine
  Automatic       12               7
  Manual           6               7
> # Get a boxplot using base R
> boxplot(mpg ~ am, data = mtcars)
> # Get a table using expss - there is some note about some restrictions
> use_labels(mtcars, table(am, vs))
            Engine
Transmission V-engine Straight engine
   Automatic       12               7
   Manual           6               7
> # Linear Regression and results, This is much nicer output from base R
> use_labels(mtcars, lm(mpg ~ wt + hp + qsec)) %>% summary

Call:
lm(formula = `Miles/(US) gallon` ~ `Weight (1000 lbs)` + `Gross horsepower` + 
    `1/4 mile time`)

Residuals:
LABEL: Miles/(US) gallon 
VALUES:
-3.8591, -1.6418, -0.4636, 1.194, 5.6092

Coefficients:
                    Estimate Std. Error t value Pr(>|t|)    
(Intercept)         27.61053    8.41993   3.279  0.00278 ** 
`Weight (1000 lbs)` -4.35880    0.75270  -5.791 3.22e-06 ***
`Gross horsepower`  -0.01782    0.01498  -1.190  0.24418    
`1/4 mile time`      0.51083    0.43922   1.163  0.25463    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.578 on 28 degrees of freedom
Multiple R-squared:  0.8348,	Adjusted R-squared:  0.8171 
F-statistic: 47.15 on 3 and 28 DF,  p-value: 4.506e-11

> # ggplot2 graphics with variables and value labels:
> library(ggplot2, warn.conflicts = FALSE)
> use_labels(mtcars, {
+   # '..data' is shortcut for all 'mtcars' data.frame inside expression 
+   ggplot(..data) +
+     geom_point(aes(y = mpg, x = wt, color = qsec)) +
+     facet_grid(am ~ vs)
+ })
> ## Not working on Monday, October 15, 2018
> # just simple crosstabulation, similar to base R 'table' function
> cro(mtcars$am, mtcars$vs) # Get an error - could not find function "name_dots"
Error in name_dots(...) : could not find function "name_dots"

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.0.0 expss_0.8.7  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18       rstudioapi_0.7     bindr_0.1.1        knitr_1.20         magrittr_1.5       tidyselect_0.2.4  
 [7] munsell_0.5.0      colorspace_1.3-2   R6_2.2.2           rlang_0.2.2        dplyr_0.7.6        stringr_1.3.1     
[13] plyr_1.8.4         tools_3.5.1        grid_3.5.1         htmlTable_1.12     checkmate_1.8.5    data.table_1.11.4 
[19] gtable_0.2.0       withr_2.1.2        htmltools_0.3.6    matrixStats_0.54.0 assertthat_0.2.0   yaml_2.1.19       
[25] lazyeval_0.2.1     digest_0.6.15      tibble_1.4.2       bindrcpp_0.2.2     reshape2_1.4.3     purrr_0.2.5       
[31] htmlwidgets_1.2    glue_1.2.0         labeling_0.3       stringi_1.1.7      pillar_1.2.3       compiler_3.5.1    
[37] scales_0.5.0       backports_1.1.2    foreign_0.8-70     pkgconfig_2.0.1   
> 
[Feedback on expss failure.txt](https://github.com/gdemin/expss/files/2483865/Feedback.on.expss.failure.txt)

**Comment by gdemin** [comment] 2018-10-21 10:53
@gnkitchen11 Thank you for detailed description of the error. Nevertheless I still can't reproduce this bug. I will try on other systems but it seems rather strange for me. I don't use `name_dots` in the `expss` so something is going wrong inside data.table.  Could you update your data.table installation via `install.packages("data.table")`?  The latest version is `data.table_1.11.8` while you are using 1.11.4
On my side I will include `name_dots` function in the expss in the next release with the hope that it will solve the issue.

**Comment by wck01** [comment] 2018-10-23 02:44
I tried the codes from Jrakru. I didn't find any errors. It works and the tables output is fine. I'm using latest data.table 1.11.8.

**Comment by wck01** [comment] 2018-10-29 07:42
One of my colleagues got the same name_dots(...) error. That computer used data.table 1.10.4.3. After update to latest version 1.11.8, expss works as normal. So, I think this is due to old version of data.table.

**Comment by gnkitchen11** [comment] 2018-10-29 18:13
Thanks, everyone for your help. Sorry I am so slow responding. I updated data.table as suggested to 1.11.8 and now everything is working fine.

**Comment by gdemin** [comment] 2018-10-29 18:34
@wck01 Many thanks for help:)

**Comment by JohnsonBrent** [comment] 2018-11-01 21:18
FWIW, I got the same error today:
`Error in name_dots(...) : could not find function "name_dots"`
It didn't go away after updating to the latest version of data.table.  Rather, it got fixed by updating data.table AND updating to the latest version of expss here on github rather than the version presently on CRAN:
`devtools::install_github("gdemin/expss")`

Thanks!

**Comment by gdemin** [comment] 2018-11-01 21:31
@JohnsonBrent  Bug becomes even more mysterious because version on the Github in the master branch is the same version as on the CRAN. I usually push new version before the release to the branch "develop" and there is no guarantee that it will be build successfully.

**Closed** 2018-11-15 21:36 UTC
