### ISSUE TITLE
Create Nets for Rows

### ISSUE THREAD

**Issue by abrunk** [gdemin/expss#16] opened 2018-12-10 02:21 UTC
First off, this is a fantastic package and meets a tremendous need for good open-source crosstabulation software that has existed for a long time.  Very impressed by the amount of thought and work that has gone into it.

I'm struggling with something that I feel like should be straightforward, but can't figure out after reviewing the readme.  I'm not sure if there's a way to create row nets and incorporate those into a crosstab report.

Example: In the github.io page, one of the examples is a variable with response options:

Extremely poor
Very poor
Quite poor
Neither good nor poor
Quite good
Very good
Excellent

If one wanted to display column percentages for each of those rows, but also create two summary rows in order to net the three 'good' options and three 'poor' options and generate a report as follows, how would one go about it:

TOTAL Poor (Sum of responses 1:3)
TOTAL Good (Sum of responses 5;7)

Extremely poor
Very poor
Quite poor
Neither good nor poor
Quite good
Very good
Excellent

**Comment by zelihay** [comment] 2018-12-10 19:30
Thanks for the question and the answer :) I've been trying to find a solution for this.

Based on your answer I've managed to write codes for only one question in the dataset. This can be help for others who are new in R like me :) 

/-change dataset and Question in codes-/

 set.seed(123)
 dataset = compute(dataset, {
                                T3Box = recode(Question, 1:3 ~ -1, 5:7 ~ -2)
                                 val_lab(T3Box) = c("B3B" = -1, "T3B" = -2)
	                              })

/-for percent result-/

     dataset %>%
     tab_cells(mrset(Question, T3Box)) %>%
     tab_cols(total()) %>%
     tab_stat_cpct() %>%
     tab_pivot()

**Comment by robertogilsaura** [comment] 2018-12-10 21:21
Ok, thanks to the group. It is certainly a luxury to be able to learn with
you. I am happy to know @gdemin that NETS development is a priority for you
(I already asked Top and Bottom at the time) and now I see how to solve
this problem with your answer to the @abrunk solution and the contribution
of @zelihay.
-.-.-.-.-
*Roberto Gil Saura  ** <https://www.facebook.com/robertogilsaura>
<https://twitter.com/robertogilsaura>
<https://www.linkedin.com/in/robertogilsaura/> *

* <https://www.investigaonline.com>*
---
Este mensaje y los ficheros anexos que, en su caso, incorpore pueden
contener información confidencial o de uso exclusivamente interno de
investigaonline.com, sujeto a secreto profesional. Si usted lo recibe por
error o considera que no es el destinatario del mismo, debe destruirlo y
comunicar al emisor esta circunstancia, no pudiendo en ningún caso
distribuir, divulgar ni copiar el mensaje.

**Comment by robertogilsaura** [comment] 2019-05-21 05:15
Hi @gdemin .

I continue to use this package in my classes at the University in the subject of Market Research, and the situation of the integrated NETS among the codes of a variable is raised again.

Is there a new deadline for this development in your roadmap?

Thanks in advance.

**Comment by gdemin** [comment] 2019-05-21 11:19
Hi @robertogilsaura,
Sorry for delay. I work on this issue. Now I hope I will release new version till the end of June.

**Comment by robertogilsaura** [comment] 2019-05-21 12:55
Hi @gdemin. Great news for a great work... I look forward to this release.

**Comment by gdemin** [comment] 2019-07-01 07:30
Version 0.9.0 with nets and subtotals is on its way to CRAN. Original example looks like:
```R
set.seed(123)
overall_liking = sample(1:7, 100, replace = TRUE)
var_lab(overall_liking) = "Seven-point scales"
val_lab(overall_liking) = num_lab("
     1 Extremely poor
     2 Very poor
     3 Quite poor
     4 Neither good nor poor
     5 Quite good
     6 Very good
     7 Excellent
")


cro_cpct(subtotal(overall_liking, 
                  "TOTAL Good (Sum of responses 5:7)" = 5:7,
                  "TOTAL Poor (Sum of responses 1:3)" = 1:3,
                  position = "top"
                  ))
  # |                    |                                   | #Total |
  # | ------------------ | --------------------------------- | ------ |
  # | Seven-point scales | TOTAL Poor (Sum of responses 1:3) |     45 |
  # |                    | TOTAL Good (Sum of responses 5:7) |     45 |
  # |                    |                    Extremely poor |     18 |
  # |                    |                         Very poor |     12 |
  # |                    |                        Quite poor |     15 |
  # |                    |             Neither good nor poor |     10 |
  # |                    |                        Quite good |     13 |
  # |                    |                         Very good |     16 |
  # |                    |                         Excellent |     16 |
  # |                    |                      #Total cases |    100 |
```

`subtotal` adds subtotal to set of categories, `net` replaces categories with their net value. If you provide named arguments then name will be used as label for subtotal. In other case labels will be automatically generated taking into account arguments `new_label` and `prefix`.

Examples:
```R
library(expss)
ol = c(1:7, 99)
var_lab(ol) = "Liking"
val_lab(ol)  = num_lab("
                     1 Disgusting
                     2 Very Poor
                     3 Poor
                     4 So-so
                     5 Good
                     6 Very good
                     7 Excellent
                     99 Hard to say
                     ")
                     
cro(subtotal(ol, TOP = 6:7, BOTTOM = 1:3, position = "top"))
# autolabelling
cro(subtotal(ol, 6:7, 1:3))
# replace original codes and another way of autolabelling
cro(net(ol, 6:7, 1:3, new_label = "range", prefix = "NET "))

# character variable and criteria usage
items = c("apple", "banana", "potato", "orange", "onion", "tomato", "pineapple")
cro(
    subtotal(items, 
             "TOTAL FRUITS"     = like("*ap*") | like("*an*"), 
             "TOTAL VEGETABLES" = like("*to*") | like("*on*"), 
             position = "bottom")
)

# 'tab_net_*' usage
data(mtcars)
mtcars = apply_labels(mtcars,
                      mpg = "Miles/(US) gallon",
                      am = "Transmission",
                      am = c("Automatic" = 0,
                             "Manual"=1),
                      gear = "Number of forward gears",
                      gear = c(
                          One = 1,
                          Two = 2,
                          Three = 3,
                          Four = 4,
                          Five = 5
                      )
)
mtcars %>% 
    tab_cells(mpg) %>% 
    tab_net_cells("Low mpg" = less(mean(mpg)), "High mpg" = greater_or_equal(mean(mpg))) %>% 
    tab_cols(total(), am) %>% 
    tab_stat_cases() %>% 
    tab_pivot()

mtcars %>% 
    tab_cells(mpg) %>% 
    tab_rows(gear) %>%
    tab_subtotal_rows(1:2, 3:4, "5 and more" = greater(4)) %>% 
    tab_stat_mean() %>% 
    tab_pivot()
```

**Comment by robertogilsaura** [comment] 2019-07-01 07:37
Great!!!! Thanks a lot... I will test it quickly
-.-.-.-.-
*Roberto Gil Saura  ** <https://www.facebook.com/robertogilsaura>
<https://twitter.com/robertogilsaura>
<https://www.linkedin.com/in/robertogilsaura/> *

* <https://www.investigaonline.com>*
---
Este mensaje y los ficheros anexos que, en su caso, incorpore pueden
contener información confidencial o de uso exclusivamente interno de
investigaonline.com, sujeto a secreto profesional. Si usted lo recibe por
error o considera que no es el destinatario del mismo, debe destruirlo y
comunicar al emisor esta circunstancia, no pudiendo en ningún caso
distribuir, divulgar ni copiar el mensaje.

**Comment by robertogilsaura** [comment] 2019-07-01 11:32
Hi @gdemin . I have tested the main characteristics contributed, in relation to the NETS and SUBTOTALS and a couple of question arises. 
(1) How can we make the sorting options run within the group?  
(2) How can each code appear in its SUBTOTAL? 

Note: Codes 15 and 21, appear in the database in the second wave. I can't control the sequence of codes in the raw data.

The example is:

```
library(expss)
set.seed(311265)

brand <- sample(c(1:9),100, replace=TRUE)
gender <- sample(1:2, 100, replace=TRUE)
wave <- rep(1, 50)
data2018 <- data.frame(gender, brand, wave)

brand <- sample(c(1:9, 15, 21),50, replace=TRUE)
gender <- sample(1:2, 50, replace=TRUE)
wave <- rep(2,50)
data2019 <- data.frame(gender, brand, wave)

data <- rbind(data2018, data2019)

val_lab(data$gender) <- c("female"=2, "male"=1)
val_lab(data$brand) <- c("AA1" = 1, "AA2" = 2, "AA3" = 3, "AA4"=15, "AA5"=21, "BB1" = 4, "BB2" = 5, "BB3" = 6, "CC1" = 7, "CC2" = 8, "CC3" = 9)
val_lab(data$wave) <- c("Wave 2018"=1, "Wave 2019"=2)

data %>%
    tab_cols(wave %nest% gender) %>%
    tab_cells(brand) %>%
    #tab_subtotal_cells(c(1:3,15,21), 4:6, 7:9, position = "above", prefix = "GROUP ", new_label = "range", add=TRUE) %>%
    tab_stat_cases() %>%
    tab_pivot() #%>%
    #tab_sort_desc(excluded_rows = "#", na.last = FALSE)

```
I need the order of codes within group, but the result is

```
 |       |                 | Wave 2018 |        | Wave 2019 |        |
 |       |                 |      male | female |      male | female |
 | ----- | --------------- | --------- | ------ | --------- | ------ |
 | brand | GROUP AA1 - AA5 |         9 |     24 |         9 |     12 |
 |       |             AA1 |         4 |      7 |         4 |      2 |
 |       |             AA2 |         1 |     11 |           |      2 |
 |       |             AA3 |         4 |      6 |         2 |      1 |
 |       | GROUP BB1 - BB3 |        16 |     17 |         8 |      3 |
 |       |             BB1 |         3 |      5 |           |        |
 |       |             BB2 |         5 |      4 |         3 |      2 |
 |       |             BB3 |         8 |      8 |         5 |      1 |
 |       | GROUP CC1 - CC3 |        22 |     12 |        11 |      7 |
 |       |             CC1 |         4 |      3 |         6 |      1 |
 |       |             CC2 |         7 |      5 |         2 |      3 |
 |       |             CC3 |        11 |      4 |         3 |      3 |
 |       |             AA4 |           |        |         1 |      4 |
 |       |             AA5 |           |        |         2 |      3 |
 |       |    #Total cases |        47 |     53 |        28 |     22 |
```

without sorting ...

```
 |       |                 | Wave 2018 |        | Wave 2019 |        |
 |       |                 |      male | female |      male | female |
 | ----- | --------------- | --------- | ------ | --------- | ------ |
 | brand |             AA4 |           |        |         1 |      4 |
 |       |             AA5 |           |        |         2 |      3 |
 |       | GROUP CC1 - CC3 |        22 |     12 |        11 |      7 |
 |       | GROUP BB1 - BB3 |        16 |     17 |         8 |      3 |
 |       |             CC3 |        11 |      4 |         3 |      3 |
 |       | GROUP AA1 - AA5 |         9 |     24 |         9 |     12 |
 |       |             BB3 |         8 |      8 |         5 |      1 |
 |       |             CC2 |         7 |      5 |         2 |      3 |
 |       |             BB2 |         5 |      4 |         3 |      2 |
 |       |             AA1 |         4 |      7 |         4 |      2 |
 |       |             AA3 |         4 |      6 |         2 |      1 |
 |       |             CC1 |         4 |      3 |         6 |      1 |
 |       |             BB1 |         3 |      5 |           |        |
 |       |             AA2 |         1 |     11 |           |      2 |
 |       |    #Total cases |        47 |     53 |        28 |     22 |
```
Is there any way to maintain each group with a sorting block?

Thanks in advance. New functionalities are wonderful !!!

**Comment by gdemin** [comment] 2019-07-01 14:18
To sort only within groups you can add your prefix ("GROUP"  ) to the excluded rows in the `tab_sort_desc`:
```R
data %>%
    tab_cols(wave %nest% gender) %>%
    tab_cells(brand) %>%
    tab_subtotal_cells(c(1:3,15,21), 4:6, 7:9, position = "above", prefix = "GROUP ", new_label = "range", add=TRUE) %>%
    tab_stat_cases() %>%
    tab_pivot() %>%
    tab_sort_desc(excluded_rows = "#|GROUP", na.last = FALSE)
```

As for second question, it seems that I need to make something for this in the future versions. But it will be tricky.  However, by now there is an ugly workaround by nesting net with subtotal:
```R
grouped_subtotal = function(x, ..., position = "below", prefix = "TOTAL ", new_label = "all"){
    args = list(...)
    names(args) = paste0("@", seq_along(args))
    args = c(list(unvr(x)), args, list(position = position))
    first = do.call(net, args)
    res = first %nest% subtotal(x, ..., position = position, prefix = prefix, new_label = new_label)
    res = drop_unused_labels(res)
    names(val_lab(res)) = gsub("^@\\d+\\|", "", names(val_lab(res)))
    res
    
}

data %>%
    tab_cols(wave %nest% gender) %>%
    tab_cells(
        grouped_subtotal(brand, c(1:3,15,21), 4:6, 7:9, position = "above", prefix = "GROUP ", new_label = "range")
        ) %>%
    tab_stat_cases() %>%
    tab_pivot() %>%
    tab_sort_desc(excluded_rows = "#|GROUP", na.last = TRUE)
# |                 | Wave 2018 |        | Wave 2019 |        |
# |                 |      male | female |      male | female |
# | --------------- | --------- | ------ | --------- | ------ |
# | GROUP AA1 - AA5 |         9 |     24 |        11 |      5 |
# |             AA1 |         4 |      7 |         4 |        |
# |             AA3 |         4 |      6 |         3 |      2 |
# |             AA2 |         1 |     11 |         1 |      1 |
# |             AA4 |           |        |         2 |      1 |
# |             AA5 |           |        |         1 |      1 |
# | GROUP BB1 - BB3 |        16 |     17 |         7 |      5 |
# |             BB3 |         8 |      8 |         2 |      1 |
# |             BB2 |         5 |      4 |         5 |      3 |
# |             BB1 |         3 |      5 |           |      1 |
# | GROUP CC1 - CC3 |        22 |     12 |        13 |      9 |
# |             CC3 |        11 |      4 |         6 |      3 |
# |             CC2 |         7 |      5 |         6 |      4 |
# |             CC1 |         4 |      3 |         1 |      2 |
# |    #Total cases |        47 |     53 |        31 |     19 |
```

**Comment by robertogilsaura** [comment] 2019-07-01 14:53
Thanks for your support and always your quick response, @gdemin. 

I will work with this function until next release or beyond.

I think it's complex to work with functions with my students. It is already difficult to make them scripting, although when they do they see the great advantages of doing it. We try use simple cases in classroom.

I look forward to those future releases.

**Thanks**.

**Comment by robertogilsaura** [comment] 2019-07-02 07:48
Hello @gdemin. I keep working with the new features and I have a problem. In the following real example (tracking on industrial bakery from Panrico, Spain), I apply the solution proposed yesterday for the NETS. There are non-sequential codes in the NETS, although the problem is the same without NETS. The codes come out by numerical series and not in the order that they have been generated in the values of the variable. This case is more complex, given that the variable is multiple.

table1 is correct, but the non-sequential codes appear in the place of the corresponding numerical series, for example, filled Donuts (code 138) when their group goes higher in the table (-NET-Donuts). I use tab_prepend_all for identify.

however, in table2, if we apply the grouped_subtotal () function since the response is multiple type, the result has some problem with the union of the codes.

Is there any solution with the same function?

I paste code and upload file ...

```

library(expss)
#setwd("~/_datos/47.nets")
data <- read_spss("P1_TOTAL.sav")

grouped_subtotal = function(x, ..., position = "below", prefix = "NET ", new_label = "all")
    {args = list(...)
    names(args) = paste0("@", seq_along(args))
    args = c(list(unvr(x)), args, list(position = position))
    first = do.call(net, args)
    res = first %nest% subtotal(x, ..., position = position, prefix = prefix, new_label = new_label)
    res = drop_unused_labels(res)
    names(val_lab(res)) = gsub("^@\\d+\\|", "", names(val_lab(res)))
    res}

table1 <- data %>% 
    tab_prepend_all() %>% 
    tab_cols(total()) %>%
    tab_cells(mrset(P1_TOTAL_1 %to% P1_TOTAL_12)) %>% 
    tab_subtotal_cells(
        mrset(P1_TOTAL_1 %to% P1_TOTAL_12),
        "La Bella Easo" = c(1, 3, 6),
        "Bollycao" = 10:12,
        "Bollycao Merienda/Clásico + Bollycao Minis" = c(10, 12),
        "Donuts" = c(20, 24, 25, 31, 138),
        "*Qé!" = c(40, 43, 44),
        "Dulcesol" = c(61, 63, 64),
        "Marcas distribuidor" = c(110, 115:118, 122),
        position = "above",
        prefix = "NET ",
        new_label = "first"
    ) %>%
    tab_stat_cases() %>% 
    tab_pivot()


table2 <- data %>% 
    tab_prepend_all() %>% 
    tab_cols(total()) %>%
    tab_cells(
        grouped_subtotal(
            mrset(P1_TOTAL_1 %to% P1_TOTAL_12),
            "La Bella Easo" = c(1, 3, 6),
            "Bollycao" = 10:12,
            "Bollycao Merienda/Clásico + Bollycao Minis" = c(10, 12),
            "Donuts" = c(20, 24, 25, 31, 138),
            "*Qé!" = c(40, 43, 44),
            "Dulcesol" = c(61, 63, 64),
            "Marcas distribuidor" = c(110, 115:118, 122),
            position = "above",
            prefix = "NET ",
            new_label = "first"
        )
    ) %>%
    tab_stat_cases() %>% 
    tab_pivot()
```

Thanks in advance.

[P1_TOTAL.zip](https://github.com/gdemin/expss/files/3348870/P1_TOTAL.zip)

**Comment by gdemin** [comment] 2019-07-03 08:03
Hmm, table2 really looks weird... By now I cannot suggest quick fix. But good news is that it seems I know how to fix inconsistent ordering. Will try on this weekend.

**Comment by gdemin** [comment] 2019-07-14 22:19
Now non-adjacent codes should be placed near each other. But there is an overlapping categories in your example:
```R
"Bollycao" = 10:12,
"Bollycao Merienda/Clásico + Bollycao Minis" = c(10, 12)
```
How would you like them to appear in the table?

And remarks about syntax. 
1. You don't need to specify variables (`mrset(P1_TOTAL_1 %to% P1_TOTAL_12)` in the `tab_subtotal_cells`. `tab_subtotal_cells` acts on the all cell variables. If you want to use subtotal only on subset of variables you can apply `subtotal` on those variables in the `tab_cells`: tab_cells(x, subtotal(y, 1:2, 3:4)) .
2. `prefix` and `new_label` arguments don't work on subtotals with specified labels, e. g. ` "La Bella Easo" = c(1, 3, 6)`.  In this case you need to explicitly specify  ` "NET La Bella Easo" = c(1, 3, 6)`.

**Comment by robertogilsaura** [comment] 2019-07-15 06:01
Hi @gdemin. I answer your question. 
The customer wants two different groupings on the same levels of code. You know that it's normal with evolutioned waves, He/she wants to regroup. 

In my opinion what would be better would be to repeat the list of codes. Therefore the result would be:

**Total Bollycao**
10 Bollycao
11 Bollycao Dokyo
12 Bollycao Minis
**Total  Bollycao Snack / Classic + Bollycao Minis**
10 Bollycao
12 Bollycao Minis

This implies repeating cases' lines but from the point of view of the analysis of the table, I think it is the most appropriate. In addition, the solution would allow a wider projection of crossed groups, being able to mix NETS with levels of codes of different NETS.

Thanks for your remarks in the syntax. They will be included in the future.

**Comment by gdemin** [comment] 2019-08-26 13:48
Version 0.9.1 with updated nets and subtotals is on its way to CRAN. Now it has more consistent ordering and support overlapping categories.

**Closed** 2019-10-11 12:23 UTC
